name: Deploy to workers
on:
  push:
    branches:
      - main
    paths:
      - 'apps/worker-scraping/**'
      - '.github/workflows/workers-deployment.yaml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3 
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/worker-scraping/"
          # projectName: tidtu # e.g. 'my-project'
          # directory:  apps/website/dist # e.g. 'dist'
          # gitHubToken: ${{ secrets.TOKEN_GITHUB }}
